#!/usr/bin/env python

RESET_GPIO = 12

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(RESET_GPIO, GPIO.OUT)

GPIO.output(RESET_GPIO, GPIO.LOW)
#time.sleep(0.1)
GPIO.output(RESET_GPIO, GPIO.HIGH)
#time.sleep(0.1)
#print("Controller is reset.")

GPIO.cleanup()
